const dateFormatter = require('./dateFormatter')

const disaggregatedPositionparser = (rawPosition) => {

  if (rawPosition.Prod_Merc_Positions_Long_ALL) {
    let disaggregatedPosition = {

      created: new Date(Date.now()),
      reportDate: new Date(dateFormatter(rawPosition.As_of_Date_In_Form_YYMMDD, 'long')),
      Market_and_Exchange_Names: rawPosition.Market_and_Exchange_Names,
      As_of_Date_In_Form_YYMMDD: rawPosition.As_of_Date_In_Form_YYMMDD,
      Report_Date_as_MM_DD_YYYY: rawPosition.Report_Date_as_MM_DD_YYYY,
      CFTC_Contract_Market_Code: rawPosition.CFTC_Contract_Market_Code,
      CFTC_Market_Code: rawPosition.CFTC_Market_Code,
      CFTC_Region_Code: rawPosition.CFTC_Region_Code,
      CFTC_Commodity_Code: rawPosition.CFTC_Commodity_Code,
      Open_Interest_All: +rawPosition.Open_Interest_All,
      Prod_Merc_Positions_Long_ALL: +rawPosition.Prod_Merc_Positions_Long_ALL,
      Prod_Merc_Positions_Short_ALL: +rawPosition.Prod_Merc_Positions_Short_ALL,
      Swap_Positions_Long_All: +rawPosition.Swap_Positions_Long_All,
      Swap__Positions_Short_All: +rawPosition.Swap__Positions_Short_All,
      Swap__Positions_Spread_All: +rawPosition.Swap__Positions_Spread_All,
      M_Money_Positions_Long_ALL: +rawPosition.M_Money_Positions_Long_ALL,
      M_Money_Positions_Short_ALL: +rawPosition.M_Money_Positions_Short_ALL,
      M_Money_Positions_Spread_ALL: +rawPosition.M_Money_Positions_Spread_ALL,
      Other_Rept_Positions_Long_ALL: +rawPosition.Other_Rept_Positions_Long_ALL,
      Other_Rept_Positions_Short_ALL: +rawPosition.Other_Rept_Positions_Short_ALL,
      Other_Rept_Positions_Spread_ALL: +rawPosition.Other_Rept_Positions_Spread_ALL,
      Tot_Rept_Positions_Long_All: +rawPosition.Tot_Rept_Positions_Long_All,
      Tot_Rept_Positions_Short_All: +rawPosition.Tot_Rept_Positions_Short_All,
      NonRept_Positions_Long_All: +rawPosition.NonRept_Positions_Long_All,
      NonRept_Positions_Short_All: +rawPosition.NonRept_Positions_Short_All,
      Change_in_Open_Interest_All: +rawPosition.Change_in_Open_Interest_All,
      Change_in_Prod_Merc_Long_All: +rawPosition.Change_in_Prod_Merc_Long_All,
      Change_in_Prod_Merc_Short_All: +rawPosition.Change_in_Prod_Merc_Short_All,
      Change_in_Swap_Long_All: +rawPosition.Change_in_Swap_Long_All,
      Change_in_Swap_Short_All: +rawPosition.Change_in_Swap_Short_All,
      Change_in_Swap_Spread_All: +rawPosition.Change_in_Swap_Spread_All,
      Change_in_M_Money_Long_All: +rawPosition.Change_in_M_Money_Long_All,
      Change_in_M_Money_Short_All: +rawPosition.Change_in_M_Money_Short_All,
      Change_in_M_Money_Spread_All: +rawPosition.Change_in_M_Money_Spread_All,
      Change_in_Other_Rept_Long_All: +rawPosition.Change_in_Other_Rept_Long_All,
      Change_in_Other_Rept_Short_All: +rawPosition.Change_in_Other_Rept_Short_All,
      Change_in_Other_Rept_Spread_All: +rawPosition.Change_in_Other_Rept_Spread_All,
      Change_in_Tot_Rept_Long_All: +rawPosition.Change_in_Tot_Rept_Long_All,
      Change_in_Tot_Rept_Short_All: +rawPosition.Change_in_Tot_Rept_Short_All,
      Change_in_NonRept_Long_All: +rawPosition.Change_in_NonRept_Long_All,
      Change_in_NonRept_Short_All: +rawPosition.Change_in_NonRept_Short_All,
      Pct_of_Open_Interest_All: +rawPosition.Pct_of_Open_Interest_All,
      Pct_of_OI_Prod_Merc_Long_All: +rawPosition.Pct_of_OI_Prod_Merc_Long_All,
      Pct_of_OI_Prod_Merc_Short_All: +rawPosition.Pct_of_OI_Prod_Merc_Short_All,
      Pct_of_OI_Swap_Long_All: +rawPosition.Pct_of_OI_Swap_Long_All,
      Pct_of_OI_Swap_Short_All: +rawPosition.Pct_of_OI_Swap_Short_All,
      Pct_of_OI_Swap_Spread_All: +rawPosition.Pct_of_OI_Swap_Spread_All,
      Pct_of_OI_M_Money_Long_All: +rawPosition.Pct_of_OI_M_Money_Long_All,
      Pct_of_OI_M_Money_Short_All: +rawPosition.Pct_of_OI_M_Money_Short_All,
      Pct_of_OI_M_Money_Spread_All: +rawPosition.Pct_of_OI_M_Money_Spread_All,
      Pct_of_OI_Other_Rept_Long_All: +rawPosition.Pct_of_OI_Other_Rept_Long_All,
      Pct_of_OI_Other_Rept_Short_All: +rawPosition.Pct_of_OI_Other_Rept_Short_All,
      Pct_of_OI_Other_Rept_Spread_All: +rawPosition.Pct_of_OI_Other_Rept_Spread_All,
      Pct_of_OI_Tot_Rept_Long_All: +rawPosition.Pct_of_OI_Tot_Rept_Long_All,
      Pct_of_OI_Tot_Rept_Short_All: +rawPosition.Pct_of_OI_Tot_Rept_Short_All,
      Pct_of_OI_NonRept_Long_All: +rawPosition.Pct_of_OI_NonRept_Long_All,
      Pct_of_OI_NonRept_Short_All: +rawPosition.Pct_of_OI_NonRept_Short_All,
      Traders_Tot_All: rawPosition.Traders_Tot_All,
      Traders_Prod_Merc_Long_All: rawPosition.Traders_Prod_Merc_Long_All,
      Traders_Prod_Merc_Short_All: rawPosition.Traders_Prod_Merc_Short_All,
      Traders_Swap_Long_All: rawPosition.Traders_Swap_Long_All,
      Traders_Swap_Short_All: rawPosition.Traders_Swap_Short_All,
      Traders_Swap_Spread_All: rawPosition.Traders_Swap_Spread_All,
      Traders_M_Money_Long_All: rawPosition.Traders_M_Money_Long_All,
      Traders_M_Money_Short_All: rawPosition.Traders_M_Money_Short_All,
      Traders_M_Money_Spread_All: rawPosition.Traders_M_Money_Spread_All,
      Traders_Other_Rept_Long_All: rawPosition.Traders_Other_Rept_Long_All,
      Traders_Other_Rept_Short_All: rawPosition.Traders_Other_Rept_Short_All,
      Traders_Other_Rept_Spread_All: rawPosition.Traders_Other_Rept_Spread_All,
      Traders_Tot_Rept_Long_All: rawPosition.Traders_Tot_Rept_Long_All,
      Traders_Tot_Rept_Short_All: rawPosition.Traders_Tot_Rept_Short_All,
      Conc_Gross_LE_4_TDR_Long_All: +rawPosition.Conc_Gross_LE_4_TDR_Long_All,
      Conc_Gross_LE_4_TDR_Short_All: +rawPosition.Conc_Gross_LE_4_TDR_Short_All,
      Conc_Gross_LE_8_TDR_Long_All: +rawPosition.Conc_Gross_LE_8_TDR_Long_All,
      Conc_Gross_LE_8_TDR_Short_All: +rawPosition.Conc_Gross_LE_8_TDR_Short_All,
      Conc_Net_LE_4_TDR_Long_All: +rawPosition.Conc_Net_LE_4_TDR_Long_All,
      Conc_Net_LE_4_TDR_Short_All: +rawPosition.Conc_Net_LE_4_TDR_Short_All,
      Conc_Net_LE_8_TDR_Long_All: +rawPosition.Conc_Net_LE_8_TDR_Long_All,
      Conc_Net_LE_8_TDR_Short_All: +rawPosition.Conc_Net_LE_8_TDR_Short_All,
      Contract_Units: rawPosition.Contract_Units,
      CFTC_SubGroup_Code: rawPosition.CFTC_SubGroup_Code,
      FutOnly_or_Combined: rawPosition.FutOnly_or_Combined,
    }
    return disaggregatedPosition;
  } else {
    return null;
  }

}

module.exports = disaggregatedPositionparser;