const dateFormatter = require('./dateFormatter')

const financialPositionParser = (rawPosition) => {

  if (rawPosition.Dealer_Positions_Long_All) {

    const financialPosition = {
      created: new Date(Date.now()),
      reportDate: new Date(dateFormatter(rawPosition.As_of_Date_In_Form_YYMMDD, 'long')),
      Market_and_Exchange_Names: rawPosition.Market_and_Exchange_Names,
      As_of_Date_In_Form_YYMMDD: rawPosition.As_of_Date_In_Form_YYMMDD,
      Report_Date_as_MM_DD_YYYY: rawPosition.Report_Date_as_MM_DD_YYYY,
      CFTC_Contract_Market_Code: rawPosition.CFTC_Contract_Market_Code,
      CFTC_Market_Code: rawPosition.CFTC_Market_Code,
      CFTC_Region_Code: rawPosition.CFTC_Region_Code,
      CFTC_Commodity_Code: rawPosition.CFTC_Commodity_Code,
      Open_Interest_All: +rawPosition.Open_Interest_All,
      Dealer_Positions_Long_All: +rawPosition.Dealer_Positions_Long_All,
      Dealer_Positions_Short_All: +rawPosition.Dealer_Positions_Short_All,
      Dealer_Positions_Spread_All: +rawPosition.Dealer_Positions_Spread_All,
      Asset_Mgr_Positions_Long_All: +rawPosition.Asset_Mgr_Positions_Long_All,
      Asset_Mgr_Positions_Short_All: +rawPosition.Asset_Mgr_Positions_Short_All,
      Asset_Mgr_Positions_Spread_All: +rawPosition.Asset_Mgr_Positions_Spread_All,
      Lev_Money_Positions_Long_All: +rawPosition.Lev_Money_Positions_Long_All,
      Lev_Money_Positions_Short_All: +rawPosition.Lev_Money_Positions_Short_All,
      Lev_Money_Positions_Spread_All: +rawPosition.Lev_Money_Positions_Spread_All,
      Other_Rept_Positions_Long_All: +rawPosition.Other_Rept_Positions_Long_All,
      Other_Rept_Positions_Short_All: +rawPosition.Other_Rept_Positions_Short_All,
      Other_Rept_Positions_Spread_All: +rawPosition.Other_Rept_Positions_Spread_All,
      Tot_Rept_Positions_Long_All: +rawPosition.Tot_Rept_Positions_Long_All,
      Tot_Rept_Positions_Short_All: +rawPosition.Tot_Rept_Positions_Short_All,
      NonRept_Positions_Long_All: +rawPosition.NonRept_Positions_Long_All,
      NonRept_Positions_Short_All: +rawPosition.NonRept_Positions_Short_All,
      Change_in_Open_Interest_All: +rawPosition.Change_in_Open_Interest_All,
      Change_in_Dealer_Long_All: +rawPosition.Change_in_Dealer_Long_All,
      Change_in_Dealer_Short_All: +rawPosition.Change_in_Dealer_Short_All,
      Change_in_Dealer_Spread_All: +rawPosition.Change_in_Dealer_Spread_All,
      Change_in_Asset_Mgr_Long_All: +rawPosition.Change_in_Asset_Mgr_Long_All,
      Change_in_Asset_Mgr_Short_All: +rawPosition.Change_in_Asset_Mgr_Short_All,
      Change_in_Asset_Mgr_Spread_All: +rawPosition.Change_in_Asset_Mgr_Spread_All,
      Change_in_Lev_Money_Long_All: +rawPosition.Change_in_Lev_Money_Long_All,
      Change_in_Lev_Money_Short_All: +rawPosition.Change_in_Lev_Money_Short_All,
      Change_in_Lev_Money_Spread_All: +rawPosition.Change_in_Lev_Money_Spread_All,
      Change_in_Other_Rept_Long_All: +rawPosition.Change_in_Other_Rept_Long_All,
      Change_in_Other_Rept_Short_All: +rawPosition.Change_in_Other_Rept_Short_All,
      Change_in_Other_Rept_Spread_All: +rawPosition.Change_in_Other_Rept_Spread_All,
      Change_in_Tot_Rept_Long_All: +rawPosition.Change_in_Tot_Rept_Long_All,
      Change_in_Tot_Rept_Short_All: +rawPosition.Change_in_Tot_Rept_Short_All,
      Change_in_NonRept_Long_All: +rawPosition.Change_in_NonRept_Long_All,
      Change_in_NonRept_Short_All: +rawPosition.Change_in_NonRept_Short_All,
      Pct_of_Open_Interest_All: +rawPosition.Pct_of_Open_Interest_All,
      Pct_of_OI_Dealer_Long_All: +rawPosition.Pct_of_OI_Dealer_Long_All,
      Pct_of_OI_Dealer_Short_All: +rawPosition.Pct_of_OI_Dealer_Short_All,
      Pct_of_OI_Dealer_Spread_All: +rawPosition.Pct_of_OI_Dealer_Spread_All,
      Pct_of_OI_Asset_Mgr_Long_All: +rawPosition.Pct_of_OI_Asset_Mgr_Long_All,
      Pct_of_OI_Asset_Mgr_Short_All: +rawPosition.Pct_of_OI_Asset_Mgr_Short_All,
      Pct_of_OI_Asset_Mgr_Spread_All: +rawPosition.Pct_of_OI_Asset_Mgr_Spread_All,
      Pct_of_OI_Lev_Money_Long_All: +rawPosition.Pct_of_OI_Lev_Money_Long_All,
      Pct_of_OI_Lev_Money_Short_All: +rawPosition.Pct_of_OI_Lev_Money_Short_All,
      Pct_of_OI_Lev_Money_Spread_All: +rawPosition.Pct_of_OI_Lev_Money_Spread_All,
      Pct_of_OI_Other_Rept_Long_All: +rawPosition.Pct_of_OI_Other_Rept_Long_All,
      Pct_of_OI_Other_Rept_Short_All: +rawPosition.Pct_of_OI_Other_Rept_Short_All,
      Pct_of_OI_Other_Rept_Spread_All: +rawPosition.Pct_of_OI_Other_Rept_Spread_All,
      Pct_of_OI_Tot_Rept_Long_All: +rawPosition.Pct_of_OI_Tot_Rept_Long_All,
      Pct_of_OI_Tot_Rept_Short_All: +rawPosition.Pct_of_OI_Tot_Rept_Short_All,
      Pct_of_OI_NonRept_Long_All: +rawPosition.Pct_of_OI_NonRept_Long_All,
      Pct_of_OI_NonRept_Short_All: +rawPosition.Pct_of_OI_NonRept_Short_All,
      Traders_Tot_All: rawPosition.Traders_Tot_All,
      Traders_Dealer_Long_All: rawPosition.Traders_Dealer_Long_All,
      Traders_Dealer_Short_All: rawPosition.Traders_Dealer_Short_All,
      Traders_Dealer_Spread_All: rawPosition.Traders_Dealer_Spread_All,
      Traders_Asset_Mgr_Long_All: rawPosition.Traders_Asset_Mgr_Long_All,
      Traders_Asset_Mgr_Short_All: rawPosition.Traders_Asset_Mgr_Short_All,
      Traders_Asset_Mgr_Spread_All: rawPosition.Traders_Asset_Mgr_Spread_All,
      Traders_Lev_Money_Long_All: rawPosition.Traders_Lev_Money_Long_All,
      Traders_Lev_Money_Short_All: rawPosition.Traders_Lev_Money_Short_All,
      Traders_Lev_Money_Spread_All: rawPosition.Traders_Lev_Money_Spread_All,
      Traders_Other_Rept_Long_All: rawPosition.Traders_Other_Rept_Long_All,
      Traders_Other_Rept_Short_All: rawPosition.Traders_Other_Rept_Short_All,
      Traders_Other_Rept_Spread_All: rawPosition.Traders_Other_Rept_Spread_All,
      Traders_Tot_Rept_Long_All: rawPosition.Traders_Tot_Rept_Long_All,
      Traders_Tot_Rept_Short_All: rawPosition.Traders_Tot_Rept_Short_All,
      Conc_Gross_LE_4_TDR_Long_All: +rawPosition.Conc_Gross_LE_4_TDR_Long_All,
      Conc_Gross_LE_4_TDR_Short_All: +rawPosition.Conc_Gross_LE_4_TDR_Short_All,
      Conc_Gross_LE_8_TDR_Long_All: +rawPosition.Conc_Gross_LE_8_TDR_Long_All,
      Conc_Gross_LE_8_TDR_Short_All: +rawPosition.Conc_Gross_LE_8_TDR_Short_All,
      Conc_Net_LE_4_TDR_Long_All: +rawPosition.Conc_Net_LE_4_TDR_Long_All,
      Conc_Net_LE_4_TDR_Short_All: +rawPosition.Conc_Net_LE_4_TDR_Short_All,
      Conc_Net_LE_8_TDR_Long_All: +rawPosition.Conc_Net_LE_8_TDR_Long_All,
      Conc_Net_LE_8_TDR_Short_All: +rawPosition.Conc_Net_LE_8_TDR_Short_All,
      Contract_Units: rawPosition.Contract_Units,
      CFTC_SubGroup_Code: rawPosition.CFTC_SubGroup_Code,
      FutOnly_or_Combined: rawPosition.FutOnly_or_Combined
    }
    return financialPosition;
  } else {
    return null;
  }

}

module.exports = financialPositionParser;