export const SET_LOADING = 'SET_LOADING';
export const GET_CONTRACTS = 'GET_CONTRACTS';
export const GET_TOP_CONTRACTS = 'GET_TOP_CONTRACTS';
export const FILTER_CONTRACTS = 'FILTER_CONTRACTS';
export const SET_SELECTED_CONTRACT_TYPE = 'SET_SELECTED_CONTRACT_TYPE';
export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';
export const UPDATE_LIST_FILTER = 'UPDATE_LIST_FILTER';
export const GET_CONTRACT_POSITIONS = 'GET_CONTRACT_POSITIONS';
export const SET_ACTIVE_WEEK = 'SET_ACTIVE_WEEK';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const PARSE_SUCCESS = 'PARSE_SUCCESS';
export const PARSE_FAIL = 'PARSE_FAIL';
export const PARSE_LOADING = 'PARSE_LOADING';