const mongoose = require('mongoose');

const financialPositionSchema = new mongoose.Schema({
  created: { type: Date, required: false },
  reportDate: { type: Date, required: false },
  Market_and_Exchange_Names: { type: String, required: false },
  As_of_Date_In_Form_YYMMDD: { type: String, required: false },
  Report_Date_as_MM_DD_YYYY: { type: String, required: false },
  CFTC_Contract_Market_Code: { type: String, required: false },
  CFTC_Market_Code: { type: String, required: false },
  CFTC_Region_Code: { type: String, required: false },
  CFTC_Commodity_Code: { type: String, required: false },
  Open_Interest_All: { type: Number, required: false },
  Dealer_Positions_Long_All: { type: Number, required: false },
  Dealer_Positions_Short_All: { type: Number, required: false },
  Dealer_Positions_Spread_All: { type: Number, required: false },
  Asset_Mgr_Positions_Long_All: { type: Number, required: false },
  Asset_Mgr_Positions_Short_All: { type: Number, required: false },
  Asset_Mgr_Positions_Spread_All: { type: Number, required: false },
  Lev_Money_Positions_Long_All: { type: Number, required: false },
  Lev_Money_Positions_Short_All: { type: Number, required: false },
  Lev_Money_Positions_Spread_All: { type: Number, required: false },
  Other_Rept_Positions_Long_All: { type: Number, required: false },
  Other_Rept_Positions_Short_All: { type: Number, required: false },
  Other_Rept_Positions_Spread_All: { type: Number, required: false },
  Tot_Rept_Positions_Long_All: { type: Number, required: false },
  Tot_Rept_Positions_Short_All: { type: Number, required: false },
  NonRept_Positions_Long_All: { type: Number, required: false },
  NonRept_Positions_Short_All: { type: Number, required: false },
  Change_in_Open_Interest_All: { type: Number, required: false },
  Change_in_Dealer_Long_All: { type: Number, required: false },
  Change_in_Dealer_Short_All: { type: Number, required: false },
  Change_in_Dealer_Spread_All:{ type: Number, required: false },
  Change_in_Asset_Mgr_Long_All:{ type: Number, required: false },
  Change_in_Asset_Mgr_Short_All: { type: Number, required: false },
  Change_in_Asset_Mgr_Spread_All:{ type: Number, required: false },
  Change_in_Lev_Money_Long_All:{ type: Number, required: false },
  Change_in_Lev_Money_Short_All: { type: Number, required: false },
  Change_in_Lev_Money_Spread_All: { type: Number, required: false },
  Change_in_Other_Rept_Long_All: { type: Number, required: false },
  Change_in_Other_Rept_Short_All:{ type: Number, required: false },
  Change_in_Other_Rept_Spread_All: { type: Number, required: false },
  Change_in_Tot_Rept_Long_All: { type: Number, required: false },
  Change_in_Tot_Rept_Short_All: { type: Number, required: false },
  Change_in_NonRept_Long_All:{ type: Number, required: false },
  Change_in_NonRept_Short_All: { type: Number, required: false },
  Pct_of_Open_Interest_All:{ type: Number, required: false },
  Pct_of_OI_Dealer_Long_All: { type: Number, required: false },
  Pct_of_OI_Dealer_Short_All: { type: Number, required: false },
  Pct_of_OI_Dealer_Spread_All:{ type: Number, required: false },
  Pct_of_OI_Asset_Mgr_Long_All:{ type: Number, required: false },
  Pct_of_OI_Asset_Mgr_Short_All: { type: Number, required: false },
  Pct_of_OI_Asset_Mgr_Spread_All:{ type: Number, required: false },
  Pct_of_OI_Lev_Money_Long_All: { type: Number, required: false },
  Pct_of_OI_Lev_Money_Short_All: { type: Number, required: false },
  Pct_of_OI_Lev_Money_Spread_All:{ type: Number, required: false },
  Pct_of_OI_Other_Rept_Long_All: { type: Number, required: false },
  Pct_of_OI_Other_Rept_Short_All:{ type: Number, required: false },
  Pct_of_OI_Other_Rept_Spread_All: { type: Number, required: false },
  Pct_of_OI_Tot_Rept_Long_All: { type: Number, required: false },
  Pct_of_OI_Tot_Rept_Short_All: { type: Number, required: false },
  Pct_of_OI_NonRept_Long_All: { type: Number, required: false },
  Pct_of_OI_NonRept_Short_All: { type: Number, required: false },
  Traders_Tot_All: { type: String, required: false, default: '<4' },
  Traders_Dealer_Long_All: { type: String, required: false, default: '<4' },
  Traders_Dealer_Short_All: { type: String, required: false, default: '<4' },
  Traders_Dealer_Spread_All: { type: String, required: false, default: '<4' },
  Traders_Asset_Mgr_Long_All: { type: String, required: false, default: '<4' },
  Traders_Asset_Mgr_Short_All: { type: String, required: false, default: '<4' },
  Traders_Asset_Mgr_Spread_All: { type: String, required: false, default: '<4' },
  Traders_Lev_Money_Long_All: { type: String, required: false, default: '<4' },
  Traders_Lev_Money_Short_All: { type: String, required: false, default: '<4' },
  Traders_Lev_Money_Spread_All: { type: String, required: false, default: '<4' },
  Traders_Other_Rept_Long_All: { type: String, required: false, default: '<4' },
  Traders_Other_Rept_Short_All: { type: String, required: false, default: '<4' },
  Traders_Other_Rept_Spread_All: { type: String, required: false, default: '<4' },
  Traders_Tot_Rept_Long_All: { type: String, required: false, default: '<4' },
  Traders_Tot_Rept_Short_All: { type: String, required: false, default: '<4' },
  Conc_Gross_LE_4_TDR_Long_All: { type: Number, required: false },
  Conc_Gross_LE_4_TDR_Short_All: { type: Number, required: false },
  Conc_Gross_LE_8_TDR_Long_All: { type: Number, required: false },
  Conc_Gross_LE_8_TDR_Short_All: { type: Number, required: false },
  Conc_Net_LE_4_TDR_Long_All: { type: Number, required: false },
  Conc_Net_LE_4_TDR_Short_All: { type: Number, required: false },
  Conc_Net_LE_8_TDR_Long_All: { type: Number, required: false },
  Conc_Net_LE_8_TDR_Short_All: { type: Number, required: false },
  Contract_Units: { type: String, required: false },
  CFTC_SubGroup_Code: { type: String, required: false },
  FutOnly_or_Combined: { type: String, required: true, enum: ["FutOnly", "Combined"]}
});


const financialPosition = mongoose.model('financialPosition', financialPositionSchema);
module.exports = financialPosition;